const k = { '0'        : ['\u2070',   '\u2080'      ],
			'1'        : ['\u00B9',   '\u2081'      ],
			'2'        : ['\u00B2',   '\u2082'      ],
			'3'        : ['\u00B3',   '\u2083'      ],
			'4'        : ['\u2074',   '\u2084'      ],
			'5'        : ['\u2075',   '\u2085'      ],
			'6'        : ['\u2076',   '\u2086'      ],
			'7'        : ['\u2077',   '\u2087'      ],
			'8'        : ['\u2078',   '\u2088'      ],
			'9'        : ['\u2079',   '\u2089'      ],
			'a'        : ['\u1d43',   '\u2090'      ],
			'b'        : ['\u1d47',   null           ],
			'c'        : ['\u1d9c',   null           ],
			'd'        : ['\u1d48',   null           ],
			'e'        : ['\u1d49',   '\u2091'      ],
			'f'        : ['\u1da0',   null           ],
			'g'        : ['\u1d4d',   null           ],
			'h'        : ['\u02b0',   '\u2095'      ],
			'i'        : ['\u2071',   '\u1d62'      ],
			'j'        : ['\u02b2',   '\u2c7c'      ],
			'k'        : ['\u1d4f',   '\u2096'      ],
			'l'        : ['\u02e1',   '\u2097'      ],
			'm'        : ['\u1d50',   '\u2098'      ],
			'n'        : ['\u207f',   '\u2099'      ],
			'o'        : ['\u1d52',   '\u2092'      ],
			'p'        : ['\u1d56',   '\u209a'      ],
			'q'        : [null,        null           ],
			'r'        : ['\u02b3',   '\u1d63'      ],
			's'        : ['\u02e2',   '\u209b'      ],
			't'        : ['\u1d57',   '\u209c'      ],
			'u'        : ['\u1d58',   '\u1d64'      ],
			'v'        : ['\u1d5b',   '\u1d65'      ],
			'w'        : ['\u02b7',   null           ],
			'x'        : ['\u02e3',   '\u2093'      ],
			'y'        : ['\u02b8',   null           ],
			'z'        : [null,        null           ],
			'A'        : ['\u1d2c',   null           ],
			'B'        : ['\u1d2e',   null           ],
			'C'        : [null,        null           ],
			'D'        : ['\u1d30',   null           ],
			'E'        : ['\u1d31',   null           ],
			'F'        : [null,        null           ],
			'G'        : ['\u1d33',   null           ],
			'H'        : ['\u1d34',   null           ],
			'I'        : ['\u1d35',   null           ],
			'J'        : ['\u1d36',   null           ],
			'K'        : ['\u1d37',   null           ],
			'L'        : ['\u1d38',   null           ],
			'M'        : ['\u1d39',   null           ],
			'N'        : ['\u1d3a',   null           ],
			'O'        : ['\u1d3c',   null           ],
			'P'        : ['\u1d3e',   null           ],
			'Q'        : [null,        null           ],
			'R'        : ['\u1d3f',   null           ],
			'S'        : [null,        null           ],
			'T'        : ['\u1d40',   null           ],
			'U'        : ['\u1d41',   null           ],
			'V'        : ['\u2c7d',   null           ],
			'W'        : ['\u1d42',   null           ],
			'X'        : [null,        null           ],
			'Y'        : [null,        null           ],
			'Z'        : [null,        null           ],         
			'+'        : ['\u207A',   '\u208A'      ],
			'-'        : ['\u207B',   '\u208B'      ],
			'='        : ['\u207C',   '\u208C'      ],
			'['        : ['\u207D',   '\u208D'      ],
			']'        : ['\u207E',   '\u208E'      ]
		}
let extras = {      
			':alpha'   : ['\u1d45',   null           ], 
			':beta'    : ['\u1d5d',   '\u1d66'      ], 
			':gamma'   : ['\u1d5e',   '\u1d67'      ], 
			':delta'   : ['\u1d5f',   null           ], 
			':epsilon' : ['\u1d4b',   null           ], 
			':theta'   : ['\u1dbf',   null           ],
			':iota'    : ['\u1da5',   null           ],
			':pho'     : [null,        '\u1d68'      ],
			':phi'     : ['\u1db2',   null           ],
			':psi'     : ['\u1d60',   '\u1d69'      ],
			':chi'     : ['\u1d61',   '\u1d6a'      ],
			':coffee'  : ['\u2615',   '\u2615'      ]
	}

String.prototype.insert = function(t, b, e){
	let parts = [this.slice(0, b), this.slice(e ? e : b)];
	return parts.join(t);
}